name: .NET Build and Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish
        run: |
          dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: bin/Release/net*/linux-x64/publish/*